### ISSUE TITLE
Nao funciona para mim a API

### ISSUE THREAD

**Issue by douglasfdev** [celso-henrique/naruto-quotes-server#2]
Quando lanço o `python3 app.py` no console ele retorna para mim:

Traceback (most recent call last):
  File "/home/dev/Área de Trabalho/DIO/NarutoServer/app.py", line 2, in <module>
    from flask import jsonify,request,Flask
ModuleNotFoundError: No module named 'flask'

Vou estar procurando mais a respeito, nao sei se é somente comigo então não sei se da para reparar isso aqui, se eu achar a solução eu comento aqui para o pessoal ver.

**Comment by douglasfdev** [comment]
Por enquanto vou tomando caminhos alternativos e consumir API da internet, achei essa daqui:

https://animechan.vercel.app/guide

**Comment by celso-henrique** [comment]
@DouglasFernandesDev parece que faltou instalar as dependências com o comando:
`pip install -r requirements.txt`

pode checar?

**Comment by douglasfdev** [comment]
Boa tarde, já tentei, mas a instalação no meu PC da erro. Não sei por qual motivo, já procurei no stackoverflow e nada.
instalei tudo que eles pediram, fiz todos os procedimentos.
Não consegui realmente.

Imagem da instalação: https://i.postimg.cc/rmtmYwVc/Captura-de-tela-de-2022-05-30-15-01-38.png

imagem do erro: https://i.postimg.cc/cL9Lxn60/Captura-de-tela-de-2022-05-30-15-02-40.png

imagem das dependências: https://i.postimg.cc/k4sy5C60/Captura-de-tela-de-2022-05-30-15-09-54.png

**Comment by douglasfdev** [comment]
Agora consegui, fiz a instalação do restante depêndencias:

```
pip install daal
pip install pathlib
pip install ruamel-yml
```

Servidor está funcionando normalmente.

Se mais alguém estiver com o mesmo problema eu fiz os procedimentos:

Instalação do Python, instalação do pip, instalação do anaconda, instalalçao do flask, instalação do numpy, instalação do daal, instalação do pathlib e do ruamel-yml

Rodei no terminal: `pip install -r requirements.txt`
Depois rodei o `python3 app.py`
